package `in`.codelif.jportal.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// picked off jportal's own screens: charcoal slate surfaces, white type, colour only where it means something.
// tonal palettes tint every surface blue, jportal never did

internal val jportalDark = darkColorScheme(
    primary = Color(0xFFA3C9FE),
    onPrimary = Color(0xFF0B1D33),
    primaryContainer = Color(0xFF1F2937),
    onPrimaryContainer = Color(0xFFFFFFFF),
    inversePrimary = Color(0xFF2563EB),
    secondary = Color(0xFFC4C5C8),
    onSecondary = Color(0xFF191C20),
    secondaryContainer = Color(0xFF2A3039),
    onSecondaryContainer = Color(0xFFE6E7E9),
    tertiary = Color(0xFF4ADE80),
    onTertiary = Color(0xFF052E16),
    tertiaryContainer = Color(0xFF14532D),
    onTertiaryContainer = Color(0xFFBBF7D0),
    background = Color(0xFF191C20),
    onBackground = Color(0xFFFFFFFF),
    surface = Color(0xFF191C20),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF2A3039),
    onSurfaceVariant = Color(0xFF95989C),
    surfaceTint = Color(0xFFA3C9FE),
    inverseSurface = Color(0xFFE6E7E9),
    inverseOnSurface = Color(0xFF191C20),
    error = Color(0xFFF87171),
    onError = Color(0xFF450A0A),
    errorContainer = Color(0xFF7F1D1D),
    onErrorContainer = Color(0xFFFECACA),
    outline = Color(0xFF4B5563),
    outlineVariant = Color(0xFF2F3540),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF2A3039),
    surfaceDim = Color(0xFF191C20),
    surfaceContainerLowest = Color(0xFF121417),
    surfaceContainerLow = Color(0xFF1D2126),
    surfaceContainer = Color(0xFF242A32),
    surfaceContainerHigh = Color(0xFF2A3039),
    surfaceContainerHighest = Color(0xFF323A45),
)

internal val jportalLight = lightColorScheme(
    primary = Color(0xFF2563EB),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE5E7EB),
    onPrimaryContainer = Color(0xFF111827),
    inversePrimary = Color(0xFFA3C9FE),
    secondary = Color(0xFF4B5563),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE5E7EB),
    onSecondaryContainer = Color(0xFF1F2937),
    tertiary = Color(0xFF16A34A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDCFCE7),
    onTertiaryContainer = Color(0xFF14532D),
    background = Color(0xFFFFFFFF),
    onBackground = Color(0xFF111827),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF111827),
    surfaceVariant = Color(0xFFE5E7EB),
    onSurfaceVariant = Color(0xFF4B5563),
    surfaceTint = Color(0xFF2563EB),
    inverseSurface = Color(0xFF1F2937),
    inverseOnSurface = Color(0xFFF9FAFB),
    error = Color(0xFFDC2626),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEE2E2),
    onErrorContainer = Color(0xFF7F1D1D),
    outline = Color(0xFF9CA3AF),
    outlineVariant = Color(0xFFD1D5DB),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFE5E7EB),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F8FA),
    surfaceContainer = Color(0xFFF1F2F5),
    surfaceContainerHigh = Color(0xFFEBEDF0),
    surfaceContainerHighest = Color(0xFFE5E7EB),
)
